name: Deployment
on: [workflow_dispatch] 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openhab-config-v1
          path: openhab/conf/